services:
  web:
    build: .
    environment:
      - FLASK_APP=taskmanager
      - FLASK_DEBUG=1
    command: sh -c "flask init-db && flask run --host=0.0.0.0"
    ports:
      - 5000:5000
    volumes:
      - .:/app
    working_dir: /app
