[project]
name = "taskmanager"
version = "1.0.0"
description = "taskmanager task"
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"

[tool.pytest.ini_options]
testpaths = ["tests"]